In [1]:
import numpy as np
import matplotlib.pyplot as plt
from reservoirpy.datasets import to_forecasting # разбиение на train/test
import reservoirpy as rpy
from reservoirpy.nodes import Reservoir, Ridge #узлы резервуара и считывающего слоя
from reservoirpy.observables import nrmse, rsquare
import json
from scipy.integrate import solve_ivp
import copy
import warnings
from nolitsa import data


dt = 0.01
x0 = [0.62225717, -0.08232857, 30.60845379]


x = data.lorenz(length=10000, sample=dt, x0=x0,
               sigma=16.0, beta=4.0, rho=45.92)[1]

#11
time = copy.deepcopy(x) #берем значения Лоренца
X = time[:,0] #берем только x
X = X.reshape(10000,1) #зачем-то 
X = 2 * (X - X.min()) / (X.max() - X.min()) - 1 #нормализация(?)

In [2]:
from nolitsa import data, lyapunov
import numpy as np
import matplotlib.pyplot as plt

dt = 0.01
x0 = [0.62225717, -0.08232857, 30.60845379]

x = data.lorenz(length=10000, sample=dt, x0=x0,
               sigma=16.0, beta=4.0, rho=45.92)[1]

#11
time = np.copy(x) #берем значения Лоренца
X = time[:,0] #берем только x


# Choose appropriate Theiler window.
window = 60

# Time delay.
tau = 13

# Embedding dimension.
dim = [5]

d = lyapunov.mle_embed(X, dim=dim, tau=tau, maxt=300, window=window)[0]


In [10]:
max(d)

3.075896171164522

In [8]:
time.shape

(10000, 3)

In [9]:
10000*0.01

100.0

In [3]:
d

array([-8.83229201e-01, -8.77473749e-01, -8.62693256e-01, -8.43489081e-01,
       -8.23344111e-01, -8.04659081e-01, -7.88929561e-01, -7.76921222e-01,
       -7.68737608e-01, -7.64150927e-01, -7.62198555e-01, -7.61142137e-01,
       -7.58265244e-01, -7.50561437e-01, -7.36398065e-01, -7.16549985e-01,
       -6.93624450e-01, -6.69986893e-01, -6.47477422e-01, -6.27293680e-01,
       -6.09929149e-01, -5.95481509e-01, -5.83628379e-01, -5.73855389e-01,
       -5.64992582e-01, -5.55318899e-01, -5.43262641e-01, -5.27520316e-01,
       -5.08303001e-01, -4.87091473e-01, -4.65324745e-01, -4.44077384e-01,
       -4.24067385e-01, -4.05574186e-01, -3.88730073e-01, -3.73470352e-01,
       -3.59915102e-01, -3.47530374e-01, -3.35176584e-01, -3.21625926e-01,
       -3.05795188e-01, -2.87471831e-01, -2.67540087e-01, -2.47205603e-01,
       -2.27062949e-01, -2.07314551e-01, -1.88270222e-01, -1.70402449e-01,
       -1.53960251e-01, -1.39112891e-01, -1.25590655e-01, -1.12698373e-01,
       -9.95833550e-02, -

In [4]:
X

array([-5.23266392, -5.86243359, -6.58847871, ..., -3.31561834,
       -3.72311402, -4.18803975])

In [5]:
X.shape

(10000,)

In [6]:
d.shape

(300,)

In [11]:
X0 = X[:3333]
d0 = lyapunov.mle_embed(X0, dim=dim, tau=tau, maxt=300, window=window)[0]

In [12]:
d0

array([-0.10560208, -0.09797937, -0.07876624, -0.05453885, -0.03026544,
       -0.00847101,  0.00972041,  0.02371008,  0.03333358,  0.03908834,
        0.0423319 ,  0.04508815,  0.05041656,  0.0616567 ,  0.08033038,
        0.10470128,  0.13151306,  0.15782996,  0.18212577,  0.2039448 ,
        0.22309707,  0.2396182 ,  0.25373255,  0.26612902,  0.27823456,
        0.29244947,  0.31118588,  0.33484051,  0.36162791,  0.38880078,
        0.41402446,  0.43652139,  0.45670553,  0.47524225,  0.49221862,
        0.50744989,  0.52117828,  0.53437821,  0.54875946,  0.56660667,
        0.58884357,  0.61411325,  0.64002234,  0.66436807,  0.68625814,
        0.70617274,  0.72482226,  0.7425565 ,  0.75924978,  0.77445697,
        0.78843596,  0.80263112,  0.81921407,  0.83923969,  0.86199383,
        0.88560319,  0.90805472,  0.92842423,  0.94699986,  0.96440434,
        0.98118587,  0.99776119,  1.01409105,  1.02994836,  1.04575062,
        1.06221786,  1.07967535,  1.09819531,  1.11773837,  1.13

In [13]:
max(d0)

3.2708611904444704

In [14]:
X0 = X[:1000]
d0 = lyapunov.mle_embed(X0, dim=dim, tau=tau, maxt=300, window=window)[0]

In [15]:
max(d0)

3.830171030561189

In [16]:
X0 = X[1000:]
d0 = lyapunov.mle_embed(X0, dim=dim, tau=tau, maxt=300, window=window)[0]
max(d0)

3.0239454219779973

In [17]:
[1,2,3][:1]

[1]

In [19]:
X0 = X[:200]
d0 = lyapunov.mle_embed(X0, dim=dim, tau=tau, maxt=300, window=window)[0]
max(d0)

3.896975369217413

In [20]:
13,92

(13, 92)

In [21]:
x = data.lorenz(length=10000, sample=dt, x0=x0,
               sigma=16.0, beta=4.0, rho=45.92)[1]

time = np.copy(x) #берем значения Лоренца
X = time[:,0] #берем только x


# Choose appropriate Theiler window.
window = 60

# Time delay.
tau = 13

# Embedding dimension.
dim = [5]

d = lyapunov.mle_embed(X, dim=dim, tau=tau, maxt=300, window=window)[0]
max(d)

3.075896171164522

In [32]:
dt = 0.01
x0 = [0.622257170, -0.08232857, 30.60845379]

x = data.lorenz(length=1000, sample=dt, x0=x0,
               sigma=16.0, beta=4.0, rho=45.92)[1]

x = [1]*10000

#11
time = np.copy(x) #берем значения Лоренца
#X = time[:,0] #берем только x


# Choose appropriate Theiler window.
window = 60

# Time delay.
tau = 13

# Embedding dimension.
dim = [5]
X0 = X[:1000]
d = lyapunov.mle_embed(X, dim=dim, tau=tau, maxt=300, window=window)[0]

Exception: Could not find any near neighbor with a nonzero distance.  Try increasing the value of maxnum.

In [28]:
max(d)

3.8624054448599643